### ISSUE TITLE
works locally, but not on a server

### ISSUE THREAD

**Issue by tomas730** [zachey01/NSWFparse#1]
The response(html not json) I receive says that the request has been blocked due to a network policy.
But why hasn't it been blocked locally if everything(code,version of nswfparse package) is the same.

**Comment by zachey01** [comment]
because the server's ip address was blacklisted on Reddit

**Comment by tomas730** [comment]
Can I do anything to make it work, maybe some kind of work-around? Or is there no way to use your package in the server side?

**Comment by zachey01** [comment]
you can use a proxy or vpn
